### ISSUE TITLE
Graphical applications cannot get the X11 display when run on older distributions than the base target

### ISSUE THREAD

**Issue by Calinou** [intoli/exodus#18]
**Operating system, Python and Exodus version:** Fedora 27, Python 3.6.4, Exodus 1.1.6
**Target OS**: Ubuntu 14.04

I successfully bundled [Godot](https://godotengine.org/) and [Minetest](https://www.minetest.net/) binaries built on Fedora 27. However, while they are able to start up (for example, the `-h` flag can be passed to display the program's help text), they cannot retrieve the X11 display.

See the Godot startup log below for an example:

```
ERROR: initialize: Condition ' !fbc ' is true. returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:121.
ERROR: initialize: Condition ' x11_window == 0 ' is true. returned: ERR_UNAVAILABLE
   At: platform/x11/os_x11.cpp:339.
```

Minetest startup log:

```
2018-02-05 18:15:17: WARNING[Main]: system-wide share not found at "/usr/local/share/minetest"
2018-02-05 18:15:17: WARNING[Main]: system-wide share not found at "/home/ubuntu/.exodus/lib/../share/minetest"
2018-02-05 18:15:17: WARNING[Main]: system-wide share not found at "/home/ubuntu/.exodus/lib/.."
2018-02-05 18:15:17: WARNING[Main]: Couldn't find a locale directory!
2018-02-05 18:15:17: ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
2018-02-05 18:15:17: WARNING[Main]: Irrlicht: No doublebuffering available.
2018-02-05 18:15:17: ERROR[Main]: Irrlicht: Fatal error, could not get visual.
2018-02-05 18:15:17: ERROR[Main]: Could not initialize game engine.
```

In contrast, [AppImages](https://appimage.org/) of the same programs built on Ubuntu 14.04 run successfully.

**Comment by sangaline** [comment]
Could you possibly run `strace ~/.exodus/bin/Minetest > minetest-strace.log 2>&1` on the machine where you're getting the error and attach the log file here?

To clarify, are you saying that AppImages built on Ubuntu 14.04 also run on Ubuntu 14.04?

**Comment by Calinou** [comment]
> To clarify, are you saying that AppImages built on Ubuntu 14.04 or ones built on a newer version, like 18.04, run successfully?

AppImages built on Ubuntu 14.04 run successfully on Ubuntu 14.04, but not ones built from more recent distributions. This is why Exodus caught my eye: to be able to distribute portable Linux binaries while benefiting from recent versions of compilers and libraries.

**Comment by Calinou** [comment]
> When I run this in a VM I get an error about the drivers not supporting the OpenGL version.

This is expected in VirtualBox since its 3D acceleration only implements OpenGL 2.1, in contrast to software fallbacks (Mesa llvmpipe) and vmWare which are able to run Godot 3.0.

**Comment by sangaline** [comment]
Do you have any thoughts on `libGLX_indirect.so.0`? Would bundling a specific implementation, like `libGLX_mesa.so`, break things on machines with different graphics card drivers?

**Comment by Calinou** [comment]
> Would bundling a specific implementation, like libGLX_mesa.so, break things on machines with different graphics card drivers?

I don't know for sure, but IIRC, that wouldn't work on systems with proprietary graphics drivers such as NVIDIA's.

**Comment by sangaline** [comment]
In that case, I unfortunately can't see any way to get around the glibc incompatibility issues for applications that require driver-specific libraries. I think that the best way to proceed here is to add a "Known Limitations" section to the documentation where the `dlopen` and `OpenGL` issues are mentioned
