### ISSUE TITLE
Conflict with other package names

### ISSUE THREAD

**Issue by sphaugh** [Intoli/exodus#2]
There is already an Exodus for managing blockchain assets. How would you prefer we name the package?

**Comment by sangaline** [comment]
It's unfortunately somewhat unavoidable that there will be overlap between project names over time. The package name for this project is actually `exodus-bundler` on PyPI to avoid overlap with existing `exodus` packages. In #3, I've added a secondary `exodus-bundler` entry point for the command-line interface. If a user has multiple executables called `exodus` installed, then they can invoke exodus via `exodus-bundler`.

**Comment by sphaugh** [comment]
That was fast, thanks!
