### ISSUE TITLE
generated sh file doesn't work with busybox tar

### ISSUE THREAD

**Issue by jrwren** [intoli/exodus#20]
Please include the following information if you're reporting an issue.

- Which operating system you're using.
  linux
- Which Python version.
  python3
- Which exodus package version.
  1.1.8
- The command that you're running (please include the `--verbose` flag so that the stack trace is included).
  exodus /usr/bin/ffmpeg (yes, I know this is crazy)
- The full output of the command.
  there is none, the command succeeds.
- Where `$BINARY` is the name of the executable that you're trying to bundle, include the outputs of the following:
    - `which $BINARY`
    - `readelf -a $BINARY`
    - `echo $PATH`
    - `echo $LD_LIBRARY_PATH`

tar: unrecognized option '--preserve-permissions'

because the target system uses busybox. :(

**Comment by sangaline** [comment]
Interesting, it seems like there are a bunch of options in [busybox's tar implementation](https://git.busybox.net/busybox/tree/archival/tar.c) that aren't mentioned in the man page. The important ones are `--strip-components` and `-p` for preserving permissions. I think that we can probably add support for both versions of `tar` relatively easily as long as those options are supported.

Out of curiosity, did you at least get a reasonable error message when this happened?

**Comment by jrwren** [comment]
Yes, the busybox tar output was visible, so `tar: unrecognized option '--preserve-permissions'` was visible somewhere.

It was a trivial work around for me to edit the .sh file and remove that option from the tar command and then everything worked.

**Comment by sangaline** [comment]
*Everything* :-)? Even ffmpeg?

**Comment by jrwren** [comment]
IIRC, yes. It was for a work project and near EOD and I'm a little tired, so maybe something didn't work, but I vaguely recall it working a couple of hours ago.  Sorry, so tired.

**Comment by sangaline** [comment]
@jwren It should work with the BusyBox tar version as of `v1.1.9`. Please let me know if you run into any other issues!
