### ISSUE TITLE
cannot handle x as a builtin

### ISSUE THREAD

**Issue by HosseinAlipour** [intoli/exodus#53]
I tried to pack `git` but after running it on remote I get:
cannot handle x as a builtin

is it work with the most application or it is an exception?
how do I make Exodus to pack `git` correctly?

- Which operating system you're using. windows
- Which Python version. v2

**Comment by sangaline** [comment]
Exodus is a tool for relocating Linux ELF binaries from one system to another. It can't be used on the Windows operating system, and this out of scope for the project.

**Comment by HosseinAlipour** [comment]
sorry for the misunderstanding, of course, I run it on a Linux distribution.

**Comment by sangaline** [comment]
Could you please include the requested information in the issue template? That information is requested because it is very difficult to debug issues like this without more context about your operating system and the command that you're running.
