### ISSUE TITLE
Dynamic discovery of dlopen'ed libraries?

### ISSUE THREAD

**Issue by piec** [intoli/exodus#54]
Hi,

Thanks for making this tool.

Do you plan to add a feature to trace a running binary on the host system and create a list of dynamically loaded libraries? It could create automatically the necessary `--add` based on an execution.

CDE ([github](https://github.com/pgbovine/CDE), [manual](http://www.pgbovine.net/cde/manual/)) does that, or rather did that because it's not been updated for a while.

Cheers,
Pierre

**Comment by sangaline** [comment]
This functionality is actually already supported by Exodus to some extent. You can pipe the output of `strace` into Exodus and it will automatically include the dynamically loaded libraries and other file resources. For example, you can run something like this.

```bash
strace -f my-command 2>&1 | exodus my-command
```

Does that cover your use case?

**Comment by piec** [comment]
Yes great :+1: , sorry I hadn't noticed it when first browsing the Readme
