### ISSUE TITLE
NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by tebello-thejane** [Intoli/exodus#7]
It would appear that this package is incompatible with Python 2.7. I'm not very familiar with Python, but judging from the comments on https://github.com/Cadair/jupyter_environment_kernels/issues/10 it appears that Python 2.7 specifically lacks `FileNotFoundError`.

**Comment by tebello-thejane** [comment]
Attempting the fix outlined in the above issue gives me the same error as https://github.com/Intoli/exodus/issues/5.

Is this application simply not compatible with Python 2, then?

**Comment by dakami** [comment]
No, it's failing in Python 3.5 too, across a couple distros.

**Comment by sangaline** [comment]
@dakami Is it still not working for you on Python 3.5 with v1.1.3 or above? There was an issue with the output of `ldd` being different on different distributions, but this should be resolved as of #10.

@tebello-thejane The test suite runs on both Python 2 and Python 3, but there are a couple of minor edge cases that aren't covered by the tests (like the `FileNotFoundError`). I'll expand the test coverage to include these and have a fully compatible version up shortly.

**Comment by sangaline** [comment]
@tebello-thejane There should be full Python 2 compatibility as of v1.1.3. Please let me know if you run into any further issues.
